/**
 * Decoding for `execute` transaction payloads.
 *
 * A stream deploy or record insert is an `execute` (action call) transaction. Its meaningful
 * content — the action name and its arguments (the deployed stream IDs, the inserted records) —
 * arrives from `kwil.txInfo(hash)` as `tx.body.payload`, a length-prefixed binary blob. This module
 * turns that blob back into a readable `{ namespace, action, arguments }`.
 *
 * The actual wire decoding is delegated to kwil-js's canonical `Utils.decodeActionExecution` /
 * `Utils.decodeValue` (the inverse of the encoders it ships), so there is a single source of truth
 * for the ActionExecution layout. This module is a thin adapter that maps kwil-js's structural output
 * (`{ dbid, action, arguments: EncodedValue[][] }`) into native JavaScript values.
 */

import { Utils } from '@trufnetwork/kwil-js';

/**
 * A decoded `execute` transaction payload.
 */
export interface DecodedTransactionPayload {
  /** The action's namespace (kwil-db's `Namespace`, usually `"main"`). */
  namespace: string;
  /** The action name, e.g. `"create_streams"` or `"insert_records"`. */
  action: string;
  /**
   * The batched calls, each an array of arguments decoded to native JavaScript values (text→string,
   * integer→bigint, bool, bytea→Uint8Array, uuid→string, numeric→string, null). A single-call
   * transaction has one inner array.
   */
  arguments: unknown[][];
}

/**
 * Decodes an `execute` transaction payload into its action name and batched arguments, each argument
 * decoded to a native JavaScript value.
 *
 * @param payload - The raw payload bytes (e.g. `txInfo(hash).data.tx.body.payload`).
 * @returns The decoded namespace, action, and native arguments.
 * @throws If the payload is truncated or uses an unsupported version (surfaced from kwil-js).
 */
export function decodeTransactionPayload(payload: Uint8Array): DecodedTransactionPayload {
  const decoded = Utils.decodeActionExecution(payload);

  return {
    namespace: decoded.dbid,
    action: decoded.action,
    arguments: decoded.arguments.map((call) => call.map((ev) => Utils.decodeValue(ev))),
  };
}

// Inline unit tests
if (import.meta.vitest) {
  const { describe, it, expect } = import.meta.vitest;

  const hexToBytes = (hex: string): Uint8Array => {
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < hex.length; i += 2) {
      bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
    }
    return bytes;
  };

  describe('decodeTransactionPayload', () => {
    it('decodes a real Go-produced ActionExecution byte-for-byte', () => {
      // Generated by kwil-db core/types.ActionExecution.MarshalBinary for:
      //   namespace "main", action "insert_records",
      //   [["stream_a", int64(100), true], ["stream_b", int64(-5), false]]
      // Pins cross-implementation parity with the Go encoder, including a negative int64.
      const goHex =
        '0000' + // uint16-LE version = 0
        '040000006d61696e' + // namespace: len=4, "main"
        '0e000000696e736572745f7265636f726473' + // action: len=14, "insert_records"
        '0200' + // numCalls = 2
        '0300' + // call 0: numArgs = 3
        '2400000000000f0000000000000000047465787400000000000100090000000173747265616d5f61' + // "stream_a"
        '2400000000000f000000000000000004696e74380000000000010009000000010000000000000064' + // int8 100
        '1d00000000000f000000000000000004626f6f6c00000000000100020000000101' + // bool true
        '0300' + // call 1: numArgs = 3
        '2400000000000f0000000000000000047465787400000000000100090000000173747265616d5f62' + // "stream_b"
        '2400000000000f000000000000000004696e7438000000000001000900000001fffffffffffffffb' + // int8 -5
        '1d00000000000f000000000000000004626f6f6c00000000000100020000000100'; // bool false

      const decoded = decodeTransactionPayload(hexToBytes(goHex));

      expect(decoded.namespace).toBe('main');
      expect(decoded.action).toBe('insert_records');
      expect(decoded.arguments).toEqual([
        ['stream_a', 100n, true],
        ['stream_b', -5n, false],
      ]);
    });

    it('decodes an action with no calls', () => {
      // uint16-LE version | namespace="" | action="create_streams" | numCalls=0
      const hex =
        '0000' +
        '00000000' +
        '0e000000' +
        '6372656174655f73747265616d73' +
        '0000';
      const decoded = decodeTransactionPayload(hexToBytes(hex));
      expect(decoded.namespace).toBe('');
      expect(decoded.action).toBe('create_streams');
      expect(decoded.arguments).toEqual([]);
    });

    it('rejects an unsupported version', () => {
      const bad = hexToBytes('0100' + '00000000' + '00000000' + '0000');
      expect(() => decodeTransactionPayload(bad)).toThrow(/version/i);
    });

    it('rejects a truncated payload', () => {
      expect(() => decodeTransactionPayload(hexToBytes('0000'))).toThrow();
    });
  });
}
