/**
 * LocalActions example — node-local (off-chain) streams via the admin port,
 * with optional operator-key authentication.
 *
 * Local streams live entirely on a single node:
 *   - no consensus broadcast, no transaction fees
 *   - implicitly owned by the node operator (data_provider is server-derived
 *     from the node's secp256k1 key — clients never supply it)
 *   - reachable through kwild's admin JSON-RPC server, NOT the gateway
 *
 * When the node has [extensions.tn_local] require_signature = "true", every
 * admin call must carry a signature recoverable to the node operator's
 * address. Export OPERATOR_KEY and the example will sign every request.
 * Without the flag, the SDK works against an unsigned node too — auth is
 * opt-in, additive on top of kwild's transport auth.
 *
 * Flow:
 *   1. Connect to the admin server (with or without an operator-key signer)
 *   2. (If a key is set) Demonstrate that a wrong key is rejected
 *   3. Create a primitive stream, insert 5 records, read them back, query the index
 *   4. Create a 2-child composed stream + taxonomy, query the weighted result,
 *      then disable the taxonomy to confirm soft-delete
 *   5. Confirm the streams appear in list_streams (data_provider is the node's
 *      own address, lowercased)
 *   6. Clean up everything
 *
 * Run against a local node spun up with `task single:start:admin` from the
 * node repo (admin RPC on http://127.0.0.1:8485). To exercise the auth path,
 * start the node with TN_LOCAL_REQUIRE_SIGNATURE=true and export the
 * operator key:
 *
 *   # 1. Start the node with auth required
 *   TN_LOCAL_REQUIRE_SIGNATURE=true task single:start:admin
 *
 *   # 2. Export the autogenerated operator key
 *   export OPERATOR_KEY="$(docker exec tn-db cat /root/.kwild/nodekey.json | jq -r '.key')"
 *
 *   # 3. Run the example
 *   npx tsx local_actions_example/main.ts
 */

import { randomBytes } from "node:crypto";
import {
  AdminClient,
  LocalActions,
  StreamId,
  StreamType,
} from "@trufnetwork/sdk-js";

const ADMIN_URL = "http://127.0.0.1:8485";

function dateToUnix(date: Date): number {
  return Math.floor(date.getTime() / 1000);
}

async function safeDelete(local: LocalActions, streamId: string): Promise<void> {
  try {
    await local.deleteStream({ streamId });
  } catch {
    // best-effort cleanup
  }
}

/**
 * Sign requests with a *different* key from the node operator's, expecting
 * the server to reject them. This is the payoff of the auth feature — proof
 * that admin port reachability alone no longer lets a caller act as the
 * operator. Any error shape other than the server's auth-envelope rejection
 * is rethrown so setup failures don't masquerade as the expected outcome.
 */
async function demonstrateWrongKeyRejection(): Promise<void> {
  const wrongKey = "0x" + randomBytes(32).toString("hex");
  console.log(
    "\n[wrong-key check] signing with a freshly generated key (NOT the operator)"
  );

  const wrongLocal = new LocalActions(new AdminClient({ adminProvider: ADMIN_URL }), {
    signer: wrongKey,
  });
  const attemptId = (await StreamId.generate("wrong-key-attempt")).getId();
  try {
    await wrongLocal.createStream({
      streamId: attemptId,
      streamType: StreamType.Primitive,
    });
  } catch (rejected) {
    const msg = rejected instanceof Error ? rejected.message : String(rejected);
    if (!msg.includes("tn_local: unauthenticated")) {
      throw rejected;
    }
    console.log(`  rejected (expected): ${msg}`);
    return;
  }
  console.error(
    "  unexpected: server ACCEPTED a wrong-key signed request — auth is broken"
  );
  process.exit(1);
}

async function main(): Promise<void> {
  const operatorKey = process.env.OPERATOR_KEY || undefined;

  const local =
    operatorKey === undefined
      ? new LocalActions(new AdminClient({ adminProvider: ADMIN_URL }))
      : new LocalActions(new AdminClient({ adminProvider: ADMIN_URL }), {
          signer: operatorKey,
        });

  if (operatorKey === undefined) {
    console.log(
      "no OPERATOR_KEY exported — running unsigned (works only on require_signature=false nodes)"
    );
  } else {
    console.log("signing requests with the exported operator key");
  }
  console.log(`connected to admin server at ${ADMIN_URL}`);

  // If the operator key is configured, prove that a different key is
  // rejected before doing real work — both for confidence and as a
  // runnable example of the property that closes the threat model.
  if (operatorKey !== undefined) {
    await demonstrateWrongKeyRejection();
  }

  const primitiveId = (await StreamId.generate("local-actions-example-primitive")).getId();
  const childAId = (await StreamId.generate("local-actions-example-child-a")).getId();
  const childBId = (await StreamId.generate("local-actions-example-child-b")).getId();
  const composedId = (await StreamId.generate("local-actions-example-composed")).getId();

  // Drop anything left from a previous run.
  for (const sid of [primitiveId, childAId, childBId, composedId]) {
    await safeDelete(local, sid);
  }

  try {
    // ─── Primitive stream ──────────────────────────────────────
    console.log(`\nprimitive stream: ${primitiveId}`);
    await local.createStream({ streamId: primitiveId, streamType: StreamType.Primitive });

    const start = new Date(Date.UTC(2024, 0, 1));
    const records = Array.from({ length: 5 }, (_, i) => {
      const t = new Date(start);
      t.setUTCDate(start.getUTCDate() + i);
      return { eventTime: dateToUnix(t), value: String(i + 1) };
    });
    await local.insertRecords({
      streamId: records.map(() => primitiveId),
      eventTime: records.map((r) => r.eventTime),
      value: records.map((r) => r.value),
    });
    console.log(`  inserted ${records.length} records`);

    const retrieved = await local.getRecord({
      streamId: primitiveId,
      fromTime: records[0].eventTime,
      toTime: records[records.length - 1].eventTime,
    });
    console.log(`  read back: ${retrieved.length} records`);
    for (const r of retrieved.slice(0, 3)) {
      console.log(`    event_time=${r.eventTime} value=${r.value}`);
    }

    const index = await local.getIndex({
      streamId: primitiveId,
      fromTime: records[0].eventTime,
      toTime: records[records.length - 1].eventTime,
    });
    // baseTime defaults to earliest event_time → first index value is 100.
    console.log(`  index[0]=${index[0].value}, index[-1]=${index[index.length - 1].value}`);

    // ─── Composed stream + taxonomy ────────────────────────────
    console.log(`\ncomposed stream: ${composedId} (children: ${childAId}, ${childBId})`);
    for (const sid of [childAId, childBId]) {
      await local.createStream({ streamId: sid, streamType: StreamType.Primitive });
    }
    await local.createStream({ streamId: composedId, streamType: StreamType.Composed });

    const t = dateToUnix(new Date(Date.UTC(2024, 5, 1)));
    await local.insertRecords({
      streamId: [childAId, childBId],
      eventTime: [t, t],
      value: ["100", "200"],
    });

    await local.insertTaxonomy({
      streamId: composedId,
      childStreamIds: [childAId, childBId],
      weights: ["1", "1"],
      startDate: t,
    });

    const composedRecords = await local.getRecord({
      streamId: composedId,
      fromTime: t,
      toTime: t,
    });
    // Equal weights on 100 and 200 → weighted average 150.
    console.log(`  composed value at ${t}: ${composedRecords[0].value} (expect ~150)`);

    // group_sequence=1 because this is the only taxonomy ever inserted on this parent.
    await local.disableTaxonomy({ streamId: composedId, groupSequence: 1 });
    const afterDisable = await local.getRecord({
      streamId: composedId,
      fromTime: t,
      toTime: t,
    });
    console.log(`  after disable_taxonomy: ${afterDisable.length} records (expect 0)`);

    // ─── List streams ──────────────────────────────────────────
    const owned = new Set([primitiveId, childAId, childBId, composedId]);
    const listed = await local.listStreams();
    const ours = listed.filter((s) => owned.has(s.streamId));
    console.log(`\nlist_streams: ${ours.length}/${owned.size} created streams visible`);
    if (ours.length > 0) {
      console.log(`  data_provider: ${ours[0].dataProvider} (server-derived)`);
    }
  } finally {
    for (const sid of [primitiveId, childAId, childBId, composedId]) {
      await safeDelete(local, sid);
    }
    console.log("\ncleanup done.");
  }
}

main().catch((err) => {
  console.error("example failed:", err);
  process.exit(1);
});
